go

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,64 +1,63 @@
-# name: CI Workflow
+name: CI Workflow
 
-# on:
-#   pull_request:
-#     branches:
-#       - main
-#       - dev
+on:
+  pull_request:
+    branches:
+      - main
+      - dev
 
-# jobs:
-#   container-job:
-#     runs-on: ubuntu-latest
+jobs:
+  container-job:
+    runs-on: ubuntu-latest
 
-#     container:
-#       image: node:latest
+    container:
+      image: node:latest
 
-#     services:
-#       postgres:
-#         image: postgres:10.8
-#         env:
-#           DB_USER: $DB_USER
-#           DB_PASSWORD: $DB_PASSWORD
-#           DB_NAME: $DB_NAME
-#           DB_PORT: $DB_PORT
+    services:
+      postgres:
+        image: postgres:10.8
+        env:
+          DB_USER: $DB_USER
+          DB_PASSWORD: $DB_PASSWORD
+          DB_NAME: $DB_NAME
+          DB_PORT: $DB_PORT
 
-#         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
+        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
 
-#     steps:
-#       - name: Install PostgreSQL client
-#         run: apt-get update && apt-get install -y postgresql-client
+    # steps:
+    #   - name: Install PostgreSQL client
+    #     run: apt-get update && apt-get install -y postgresql-client
 
-#       - name: Wait for PostgreSQL to be ready
-#         env:
-#           DB_USER: $DB_USER
-#           DB_PASSWORD: $DB_PASSWORD
-#           DB_NAME: $DB_NAME
-#         run: |
-#           echo "$DB_USER"
-#           echo "$DB_PASSWORD"
-#           echo "$DB_NAME"
-#           until pg_isready -h postgres -p 5432 -U "$DB_USER"; do
-#             echo "Waiting for PostgreSQL to be ready..."
-#             sleep 2
-#           done
-#           if [ -z "$DB_NAME" ] || [ -z "$DB_USER" ] || [ -z "$DB_PASSWORD" ]; then
-#             echo "One or more required environment variables are not set."
-#             exit 1
-#           fi
-#           psql -h postgres -U postgres -c "CREATE DATABASE \"$DB_NAME\";"
-#           psql -h postgres -U postgres -c "CREATE ROLE \"$DB_USER\" WITH LOGIN PASSWORD '$DB_PASSWORD';"
-#           psql -h postgres -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE \"$DB_NAME\" TO \"$DB_USER\";"
+    #   - name: Wait for PostgreSQL to be ready
+    #     env:
+    #       DB_USER: $DB_USER
+    #       DB_PASSWORD: $DB_PASSWORD
+    #       DB_NAME: $DB_NAME
+    #     run: |
+    #       echo "$DB_USER"
+    #       echo "$DB_PASSWORD"
+    #       echo "$DB_NAME"
+    #       until pg_isready -h postgres -p 5432 -U "$DB_USER"; do
+    #         echo "Waiting for PostgreSQL to be ready..."
+    #         sleep 2
+    #       done
+    #       if [ -z "$DB_NAME" ] || [ -z "$DB_USER" ] || [ -z "$DB_PASSWORD" ]; then
+    #         echo "One or more required environment variables are not set."
+    #         exit 1
+    #       fi
+    #       psql -h postgres -U postgres -c "CREATE DATABASE \"$DB_NAME\";"
+    #       psql -h postgres -U postgres -c "CREATE ROLE \"$DB_USER\" WITH LOGIN PASSWORD '$DB_PASSWORD';"
+    #       psql -h postgres -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE \"$DB_NAME\" TO \"$DB_USER\";"
 
-#       - uses: actions/checkout@v3
+    #   - uses: actions/checkout@v3
 
-#       - name: Set up Node.js
-#         uses: actions/setup-node@v3
-#         with:
-#           node-version: "latest"
+    #   - name: Set up Node.js
+    #     uses: actions/setup-node@v3
+    #     with:
+    #       node-version: "latest"
 
-#       - name: Install dependencies
-#         run: npm install
-
+    # - name: Install dependencies
+    #   run: npm install
 # - name: Run Tests
 #   env:
 #     DB_USER: $DB_USER
diff --git a/.github/workflows/packer-ci.yml b/.github/workflows/packer-ci.yml
--- a/.github/workflows/packer-ci.yml
+++ b/.github/workflows/packer-ci.yml
@@ -1,66 +1,66 @@
-# name: Packer CI Workflow
+name: Packer CI Workflow
 
-# on:
-#   pull_request:
-#     branches:
-#       - main
-#       - dev
+on:
+  pull_request:
+    branches:
+      - main
+      - dev
 
-# jobs:
-#   packer-check:
-#     runs-on: ubuntu-latest
+jobs:
+  packer-check:
+    runs-on: ubuntu-latest
 
-#     steps:
-#       - name: Checkout repository
-#         uses: actions/checkout@v3
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-#       - name: Install Packer
-#         uses: hashicorp/setup-packer@v2
-#         with:
-#           packer_version: latest
+      - name: Install Packer
+        uses: hashicorp/setup-packer@v2
+        with:
+          packer_version: latest
 
-#       # Step to initialize Packer plugins
-#       - name: Initialize Packer Plugins
-#         run: |
-#           packer init ./webapp-ami.pkr.hcl
+      # Step to initialize Packer plugins
+      - name: Initialize Packer Plugins
+        run: |
+          packer init ./webapp-ami.pkr.hcl
 
-#       - name: Create Packer variables file
-#         run: |
-#           echo 'artifact_path = "application.zip"' > variables.pkrvars.hcl
+      - name: Create Packer variables file
+        run: |
+          echo 'artifact_path = "application.zip"' > variables.pkrvars.hcl
 
-#       # Step to run `packer fmt` to ensure formatting and highlight changes
-#       - name: Run Packer Fmt Check
-#         run: |
-#           packer fmt -check ./webapp-ami.pkr.hcl
-#         continue-on-error: true
-#       - name: Check for Packer Format Errors
-#         if: failure()  # Fail the workflow if formatting is not correct
-#         run: |
-#           echo "Packer formatting issues detected. Run 'packer fmt' to fix."
-#           exit 1
+      # Step to run `packer fmt` to ensure formatting and highlight changes
+      - name: Run Packer Fmt Check
+        run: |
+          packer fmt -check ./webapp-ami.pkr.hcl
+        continue-on-error: true
+      - name: Check for Packer Format Errors
+        if: failure() # Fail the workflow if formatting is not correct
+        run: |
+          echo "Packer formatting issues detected. Run 'packer fmt' to fix."
+          exit 1
 
-#       - name: Install dependencies
-#         run: npm install
+      - name: Install dependencies
+        run: npm install
 
-#       # - name: Run Integration Tests
-#       #   run: npm test
+      # - name: Run Integration Tests
+      #   run: npm test
 
-#       - name: Build Application Artifact
-#         run: |
-#           npm run build
-#           zip -r application.zip .
+      - name: Build Application Artifact
+        run: |
+          npm run build
+          zip -r application.zip .
 
-#       - name: Verify Artifact
-#         run: |
-#           if [ ! -f ./application.zip ]; then
-#             echo "Error: application.zip not found!"
-#             exit 1
-#           fi
+      - name: Verify Artifact
+        run: |
+          if [ ! -f ./application.zip ]; then
+            echo "Error: application.zip not found!"
+            exit 1
+          fi
 
-#       - name: List Directory Contents
-#         run: ls -la
+      - name: List Directory Contents
+        run: ls -la
 
-#       # Step to run `packer validate` to ensure template is valid
-#       - name: Validate Packer template
-#         id: validate
-#         run: packer validate -var "artifact_path=application.zip" webapp-ami.pkr.hcl
+      # Step to run `packer validate` to ensure template is valid
+      - name: Validate Packer template
+        id: validate
+        run: packer validate -var "artifact_path=application.zip" webapp-ami.pkr.hcl
